"""empty message

Revision ID: 2496a0fcf480
Revises: 8d28845363b8
Create Date: 2024-01-15 18:06:07.269022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2496a0fcf480'
down_revision = '8d28845363b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shap_impaint_telea_image_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shap_inpaint_ns_image_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shap_blur_image_url', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('saliency_image_url', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai', schema=None) as batch_op:
        batch_op.drop_column('saliency_image_url')
        batch_op.drop_column('shap_blur_image_url')
        batch_op.drop_column('shap_inpaint_ns_image_url')
        batch_op.drop_column('shap_impaint_telea_image_url')

    # ### end Alembic commands ###
